Создан скелет разметки
htmlacademy-htmlcss/2230657-sedona-35 pull request #2
Opened 2022-10-03 19:20 UTC by DVDzig

2022-10-05 09:05 UTC, MargoR96 requested changes
Нужны исправления

2022-10-05 09:05 UTC, MargoR96 commented on index.html
> +        <img src="" alt="Лого Sedona" class="header-logo">
Вынеси логотип из навигации, он ведет туда же что и пункт главная. Плюс он должен быть ссылкой без атрибута href.

2022-10-05 09:05 UTC, MargoR96 commented on index.html
> +        <img class="index-background" src="" alt="Вид города Седона">
Это не контентное изображение, а фоновое

2022-10-05 09:05 UTC, MargoR96 commented on index.html
> +        <h2 class="font-welcome">WELCOME</h2>
Надпись должна быть картинкой svg, весь блок, если взглянуть на макет там это показано)

2022-10-05 09:05 UTC, MargoR96 commented on index.html
> +        <img class="rectangle" src="" alt="Rectangle 125">
А что показывает эта картинка? Если тупо голубой прямоугольник, то это же не изображение а просто заливка

2022-10-05 09:05 UTC, MargoR96 commented on index.html
> +        <h3 class="visually-hidden advantages-title">НАСТОЯЩИЙ ГОРОДОК</h3>
Все плиточки должны быть списком, можно вложить один в другой

2022-10-05 09:05 UTC, MargoR96 commented on index.html
> +            <img class="rectangle" src="" alt="Rectangle 125">
Здесь аналогично, это заливка а не картинка. Поправь во всех пунктах списка, пожалуйста.

2022-10-05 09:05 UTC, MargoR96 commented on index.html
> +        <img class="photo-2" src="" alt="Вид каньона">
Здесь должно единообразно с первыми плиточками с картинкой.
Т.е если делаешь текст - картинка, то и во втором случае так же. Потом атрибут order сделаешь и все.

2022-10-05 09:05 UTC, MargoR96 commented on index.html
> +            <img class="home" src="" alt="Жильё">
Это тоже не контентное изображение, их нужно будет добавлять через псевдоэлемент. Исправь, пожалуйста во всех местах.

2022-10-05 09:05 UTC, MargoR96 commented on index.html
> +          <input class="field" placeholder="Ваш e-mail" type="email" name="newsletter-email" id="newsletter-email"
у каждого input должен быть label, добавь его и скрой

2022-10-05 09:05 UTC, MargoR96 commented on index.html
> +      <section class="subscribe">
Здесь будет блок aside, потому что имеет косвенное отношение к контенту

2022-10-05 09:05 UTC, MargoR96 commented on index.html
> +        <img class="logo-htmlacademy" src="" alt="Лого htmlacademy">
Тут должно вести на сайт Академии, глянь в демо, там один в один

2022-10-07 10:48 UTC, DVDzig commented on index.html
> +        <img src="" alt="Лого Sedona" class="header-logo">
Сделано

2022-10-07 10:57 UTC, DVDzig commented on index.html
> +        <img class="index-background" src="" alt="Вид города Седона">
Сделано

2022-10-07 11:00 UTC, DVDzig commented on index.html
> +        <h2 class="font-welcome">WELCOME</h2>
Сделано

2022-10-07 11:08 UTC, DVDzig commented on index.html
> +        <img class="rectangle" src="" alt="Rectangle 125">
Сделано

2022-10-07 11:08 UTC, DVDzig commented on index.html
> +        <h3 class="visually-hidden advantages-title">НАСТОЯЩИЙ ГОРОДОК</h3>
Сделано

2022-10-07 11:09 UTC, DVDzig commented on index.html
> +        <img class="photo-2" src="" alt="Вид каньона">
Сделано

2022-10-07 11:12 UTC, DVDzig commented on index.html
> +            <img class="home" src="" alt="Жильё">
Сделано

2022-10-07 11:16 UTC, DVDzig commented on index.html
> +          <input class="field" placeholder="Ваш e-mail" type="email" name="newsletter-email" id="newsletter-email"
Сделано

2022-10-07 11:18 UTC, DVDzig commented on index.html
> +      <section class="subscribe">
Сделано

2022-10-07 19:05 UTC, MargoR96 requested changes
Есть еще несколько недочетов

2022-10-07 19:05 UTC, MargoR96 commented on index.html
> +        <img class="index-background" src="images\main-img.jpg" alt="">
Это изображение должно быть использовано в качестве background при стилизации, это не контентное изображение

2022-10-07 19:05 UTC, MargoR96 commented on index.html
> +            <img class="home" src="images\advantages-home.svg" width="75" height="72" alt="">
Эти изображения не контентные, вставляются как псевдо элемент при стилизации, убери пожалуста во всех элементах списка

2022-10-11 15:34 UTC, MargoR96 approved these changes

2022-10-11 15:35 UTC, merged