Добавление стилей
htmlacademy-htmlcss/2230657-sedona-35 pull request #3
Opened 2022-10-16 19:42 UTC by DVDzig

2022-10-17 15:00 UTC, MargoR96 requested changes

2022-10-17 15:00 UTC, MargoR96 commented on index.html
>          </h2>
а почему ты убрал картинку svg?

2022-10-17 15:00 UTC, MargoR96 commented on styles/styles.css
> +  background-color: white;
Задний фон у сайта серый, поменяй пожалуйста

2022-10-17 15:00 UTC, MargoR96 commented on styles/styles.css
> +  flex-direction: row;
это значение по умолчанию, можно не указывать

2022-10-17 15:00 UTC, MargoR96 commented on styles/styles.css
> +  flex-direction: row;
это значение по умолчанию, можно не указывать

2022-10-17 15:00 UTC, MargoR96 commented on styles/styles.css
> +  flex-direction: row;
это значение по умолчанию, можно не указывать

2022-10-30 08:07 UTC, DVDzig commented on styles/styles.css
> +  background-color: white;
Исправлено

2022-10-30 08:07 UTC, DVDzig commented on styles/styles.css
> +  flex-direction: row;
Исправлено

2022-10-30 08:45 UTC, DVDzig reviewed
Сделаны исправления

2022-10-31 17:30 UTC, merged

2022-11-02 17:39 UTC, DVDzig reviewed
Сетка страниц и крупных блоков на флексахСетка страниц и крупных блоков на флексах