Сетка страниц и крупных блоков на флексах
htmlacademy-htmlcss/2230657-sedona-35 pull request #4
Opened 2022-11-02 17:51 UTC by DVDzig

2022-11-02 19:12 UTC, DVDzig reviewed
Подключены гриды

2022-11-03 17:02 UTC, MargoR96 requested changes

2022-11-03 17:02 UTC, MargoR96 commented on styles/styles.css
>  .background-image {
background-image: url("/images/main-img.jpg");
Неверный путь, проверь везде

2022-11-04 05:41 UTC, DVDzig reviewed
Исправление путей

2022-11-04 06:37 UTC, MargoR96 requested changes

2022-11-04 06:37 UTC, MargoR96 commented on index.html
> -      <link rel="stylesheet" href="styles/styles.css">
В правильное написание пути "..\путь"

2022-11-05 20:12 UTC, DVDzig reviewed
Исправления и общая доработка)

2022-11-08 20:20 UTC, DVDzig reviewed
Исправлены пути, сделана првоерка на валидаторИсправлены пути, сделана првоерка на валидатор

2022-11-09 10:34 UTC, MargoR96 commented
![image](https://user-images.githubusercontent.com/86987540/200807760-163051d2-bcd3-4349-9dfb-f155acc1f82a.png)
Явно что то лишнее)

2022-11-09 10:43 UTC, MargoR96 commented
![image](https://user-images.githubusercontent.com/86987540/200809501-078def8b-f71b-4719-ba76-c69af604aa60.png)
Переполнение не работает, поправь пожалуйста

2022-11-09 10:52 UTC, MargoR96 commented
![image](https://user-images.githubusercontent.com/86987540/200811292-c5a6f613-e012-49af-a97d-04db755606cb.png)
Картинка должна быть как задний фон у класса frame1
Цифры нельзя в классах

2022-11-09 10:57 UTC, MargoR96 commented
![image](https://user-images.githubusercontent.com/86987540/200812344-777db833-cc1e-413f-8c2f-ab02f0a72fc3.png)
тут выпало из-за того что margin схлопнулся, нужен паддинг

2022-11-10 19:26 UTC, DVDzig reviewed
Исправления

2022-11-11 17:48 UTC, DVDzig reviewed
Исправления_11.11.2022

2022-11-13 10:16 UTC, merged